//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing;

namespace lab2.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder",
        "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;
        public static Bitmap dog1=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\dog1.png");
        public static Bitmap cat1=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\cat1.png");
        public static Bitmap parrot1=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\parrot1.png");
        public static Bitmap dog2=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\dog2.png");
        public static Bitmap cat2=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\cat2.png");
        public static Bitmap parrot2=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\parrot2.jpg");
        public static Bitmap dog3=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\dog3.png");
        public static Bitmap cat3=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\cat3.png");
        public static Bitmap parrot3=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\parrot3.png");
        public static Bitmap dog4=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\dog4.png");
        public static Bitmap cat4=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\cat4.png");
        public static Bitmap parrot4=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\parrot4.png");
        public static Bitmap dog5=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\dog5.png");
        public static Bitmap cat5=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\cat5.png");
        public static Bitmap parrot5=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\parrot5.png");
        public static Bitmap cow=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\cow.png");
        public static Bitmap penguin=new Bitmap("D:\\Study\\OOP\\lab2\\lab2\\lab2\\Images\\penguin.png");

        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState
            .Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager("lab2.Properties.Resources",
                            typeof(Resources).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState
            .Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
    }
}